{
 "title": "LVS (Linux Virtual Servers) JSON RAW",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "node",
    "label": "Balancer:",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   { "name": "25_hex", "query": "00000019" },
   { "name": "143_hex", "query": "0000008F" },
   { "name": "443_hex", "query": "000001BB" },
   { "name": "465_hex", "query": "000001D1" },
   { "name": "587_hex", "query": "0000024B" },
   { "name": "993_hex", "query": "000003E1" },
   { "name": "5222_hex", "query": "00001466" },
   { "name": "5223_hex", "query": "00001467" },
   { "name": "5229_hex", "query": "0000146D" },
   {
    "name": "node_ip",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "port",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "target_ports",
    "label": "Loadbalancers target ports",
    "query": "25 : 00000019, 143 : 0000008F, 443 : 000001BB, 465 : 000001D1, 587 : 0000024B, 993 : 000003E1, 5222 : 00001467, 5223 : 00001467, 5229 : 0000146D"
   },
   {
    "name": "remote_target",
    "label": "Remote  targets",
    "query": {
     "query": "label_values(node_ipvs_backend_weight, remote_address)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "LVS Total connections",
   "type": "graph",
   "description": "shows the total number of connections made",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_ipvs_connections_total{job=~\"$job\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LVS Total data",
   "type": "graph",
   "description": "Shows the total amount of incoming/outocming data",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_ipvs_incoming_bytes_total{job=~\"$job\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Incoming {{instance}}"
    },
    {
     "expr": "rate(node_ipvs_outgoing_bytes_total{job=~\"$job\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Outgoing {{instance}}"
    }
   ]
  },
  {
   "title": "LVS Total packets",
   "type": "graph",
   "description": "Shows the total amount of incoming/outocoming packets",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_ipvs_incoming_packets_total{job=~\"$job\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Incoming {{instance}}"
    },
    {
     "expr": "rate(node_ipvs_outgoing_packets_total{job=~\"$job\", instance=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Outgoing {{instance}}"
    }
   ]
  },
  {
   "title": "LVS Active connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_ipvs_backend_connections_active{job=~\"$job\", instance=~\"$node\", local_mark=\"$143_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:143"
    },
    {
     "expr": "node_ipvs_backend_connections_active{job=~\"$job\", instance=~\"$node\", local_mark=\"$25_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:25"
    },
    {
     "expr": "node_ipvs_backend_connections_active{job=~\"$job\", instance=~\"$node\", local_mark=\"$443_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:443"
    },
    {
     "expr": "node_ipvs_backend_connections_active{job=~\"$job\", instance=~\"$node\", local_mark=\"$465_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:465"
    },
    {
     "expr": "node_ipvs_backend_connections_active{job=~\"$job\", instance=~\"$node\", local_mark=\"$587_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:587"
    },
    {
     "expr": "node_ipvs_backend_connections_active{job=~\"$job\", instance=~\"$node\", local_mark=\"$993_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:993"
    },
    {
     "expr": "node_ipvs_backend_connections_active{job=~\"$job\", instance=~\"$node\", local_mark=\"$5222_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:5222"
    },
    {
     "expr": "node_ipvs_backend_connections_active{job=~\"$job\", instance=~\"$node\", local_mark=\"$5223_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:5223"
    },
    {
     "expr": "node_ipvs_backend_connections_active{job=~\"$job\", instance=~\"$node\", local_mark=\"$5229_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:5229"
    }
   ]
  },
  {
   "title": "LVS InActive connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_ipvs_backend_connections_inactive{job=~\"$job\", instance=~\"$node\", local_mark=\"$143_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:143"
    },
    {
     "expr": "node_ipvs_backend_connections_inactive{job=~\"$job\", instance=~\"$node\", local_mark=\"$25_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:25"
    },
    {
     "expr": "node_ipvs_backend_connections_inactive{job=~\"$job\", instance=~\"$node\", local_mark=\"$443_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:443"
    },
    {
     "expr": "node_ipvs_backend_connections_inactive{job=~\"$job\", instance=~\"$node\", local_mark=\"$465_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:465"
    },
    {
     "expr": "node_ipvs_backend_connections_inactive{job=~\"$job\", instance=~\"$node\", local_mark=\"$587_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:587"
    },
    {
     "expr": "node_ipvs_backend_connections_inactive{job=~\"$job\", instance=~\"$node\", local_mark=\"$993_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:993"
    },
    {
     "expr": "node_ipvs_backend_connections_inactive{job=~\"$job\", instance=~\"$node\", local_mark=\"$5222_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:5222"
    },
    {
     "expr": "node_ipvs_backend_connections_inactive{job=~\"$job\", instance=~\"$node\", local_mark=\"$5223_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:5223"
    },
    {
     "expr": "node_ipvs_backend_connections_inactive{job=~\"$job\", instance=~\"$node\", local_mark=\"$5229_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:5229"
    }
   ]
  },
  {
   "title": "LVS Weight",
   "type": "stat",
   "description": "Shows weight for each real IP address and PORT",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_ipvs_backend_weight{job=~\"$job\", instance=~\"$node\", local_mark=\"$143_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:143"
    },
    {
     "expr": "node_ipvs_backend_weight{job=~\"$job\", instance=~\"$node\", local_mark=\"$25_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:25"
    },
    {
     "expr": "node_ipvs_backend_weight{job=~\"$job\", instance=~\"$node\", local_mark=\"$443_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:443"
    },
    {
     "expr": "node_ipvs_backend_weight{job=~\"$job\", instance=~\"$node\", local_mark=\"$465_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:465"
    },
    {
     "expr": "node_ipvs_backend_weight{job=~\"$job\", instance=~\"$node\", local_mark=\"$587_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:587"
    },
    {
     "expr": "node_ipvs_backend_weight{job=~\"$job\", instance=~\"$node\", local_mark=\"$993_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:993"
    },
    {
     "expr": "node_ipvs_backend_weight{job=~\"$job\", instance=~\"$node\", local_mark=\"$5222_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:5222"
    },
    {
     "expr": "node_ipvs_backend_weight{job=~\"$job\", instance=~\"$node\", local_mark=\"$5223_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:5223"
    },
    {
     "expr": "node_ipvs_backend_weight{job=~\"$job\", instance=~\"$node\", local_mark=\"$5229_hex\", remote_address=~\"$remote_target\"}",
     "legendFormat": "{{remote_address}}:5229"
    }
   ]
  }
 ]
}